# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER weiter

# 挂载目录
VOLUME /home/weiter
# 创建目录
RUN mkdir -p /home/weiter
# 指定路径
WORKDIR /home/weiter
# 复制jar文件到路径
COPY ./jar/weiter-modules-file.jar /home/weiter/weiter-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","weiter-modules-file.jar"]
